---
title: "Weather Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, message = FALSE, include = FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(dplyr)
library(ggmap)
library(geosphere)
library(lubridate)
library(patchwork)
library(leaflet)
library(leaflet.extras2)
library(shiny)
```

```{r data, message = FALSE, include = FALSE}
elk = read_csv("./data/elk.csv")

raw_weather <- read_csv("./data/raw_weather_data.csv")

weather_stations <-
  raw_weather |>
  group_by(NAME, LATITUDE, LONGITUDE) |>
  summarize(n_obs = n())

potential_stations <- 
  c("LEWIS LAKE DIVIDE, WY US", "SNAKE RIVER, WY US", "SNAKE RIVER STATION, WY US", "BASE CAMP, WY US", 
    "MORAN 5 WNW, WY US", "JACKSON 29.9 NNE, WY US", "BURRO HILL WYOMING, WY US", "MOOSE 1 NNE, WY US", 
    "MOOSE, WY US", "MOOSE .4 S, WY US", "JACKSON 12.3 NE, WY US", "JACKSON 12.2 NE, WY US", 
    "JACKSON HOLE AIRPORT, WY US", "JACKSON, WY US")

four_stations <- 
  c("SNAKE RIVER STATION, WY US", "MORAN 5 WNW, WY US", "BURRO HILL WYOMING, WY US", "MOOSE 1 NNE, WY US")

reduced_weather_stations <- 
  raw_weather |> 
  filter(NAME %in% four_stations) |> 
  group_by(NAME, LATITUDE, LONGITUDE) |> 
  summarize(n_obs = n()) |> 
  arrange(desc(n_obs))

reduced_weather <- 
  raw_weather |> 
  filter(NAME %in% four_stations)

all_data <- read_csv("./data/all_data.csv")

daily_elk <- 
  all_data |> 
  mutate(year_month_day = format(dt, "%Y-%m-%d"), 
         elk_id = as.character(elk_id)) |> 
  group_by(
    elk_id,
    year_month_day, 
    year,
    month,
    day,
    tavg,
    prcp,
    snow,
    snwd,
    tmin,
    tmax
  ) |>
  summarize(
    dist_km = sum(dist_km, na.rm = TRUE), 
    land_cover = mean(land_cover, na.rm = TRUE)
  )
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
# select weather type
weather_types = 
  daily_elk |> 
  select(-tmin, -tmax) |> 
  pivot_longer(
    tavg:snwd, 
    names_to = "weather_type", 
    values_to = "weather_value"
  ) |> 
  distinct(weather_type) |> 
  pull()

selectInput("weather_choice", label = "Select Weather Data",
            choices = weather_types, selected = "prcp")

renderPlotly({
  daily_elk |> 
    select(-tmin, -tmax) |> 
    pivot_longer(
      tavg:snwd, 
      names_to = "weather_type", 
      values_to = "weather_value"
      ) |> 
    distinct(weather_type) |> 
    pull() |> 
    filter(
      weather_type == input[["weather_choice"]]
      ) |> 
    plot_ly(
      x = ~prcp, y = ~dist_km, color = ~elk_id, type = 'scatter'
      ) |> 
    layout(xaxis = list(title = "Daily Precipitation (in)"), 
           yaxis = list(title = "Daily Distance Traveled (km)"), legend = list(title = list(text = "Elk ID")))
  })
```

Column {data-width=650}
-----------------------------------------------------------------------

### Daily Distance Traveled by Elk vs. Daily Precipitation Total

```{r}
# elk_prcp_distkm_pts <- 
#   daily_elk |> 
#   ggplot(aes(x = prcp, y = dist_km)) + 
#   geom_point(aes(color = elk_id)) + 
#   geom_smooth(se = FALSE) + 
#   labs(x = "Daily Precipitation (in)", y = "Daily Distance Traveled (km)", color = "Elk ID")
# 
# ggplotly(elk_prcp_distkm_pts)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Precipitation Totals by Month

```{r}
# point + line, separated by month and year
reduced_weather |> 
  select(c(STATION, NAME, LATITUDE, LONGITUDE, DATE, PRCP, SNOW, SNWD, TAVG)) |> 
  mutate(year = format(DATE, "%Y"), 
         month = format(DATE, "%m")) |> 
  group_by(NAME, year, month) |> 
  summarize(station_precip_total = sum(PRCP, na.rm = TRUE)) |> 
  group_by(year, month) |> 
  summarize(station_precip_total_avg = mean(station_precip_total, na.rm = TRUE)) |> 
  mutate(year_month = paste(year, month, sep = "-")) |> 
  plot_ly(
    x = ~month, y = ~station_precip_total_avg, color = ~year, group = ~year, type = 'scatter', mode = 'lines'
    ) |> 
  layout(xaxis = list(title = "Month"), 
         yaxis = list(title = "Total Precipitation (in)"), legend = list(title = list(text = "Year")))
```

### Precipitation Totals by Date (Year, Month)

```{r}
# year-month totals, separated by year
reduced_weather |> 
  select(c(STATION, NAME, LATITUDE, LONGITUDE, DATE, PRCP, SNOW, SNWD, TAVG)) |> 
  mutate(year = format(DATE, "%Y"), 
         month = format(DATE, "%m")) |> 
  group_by(NAME, year, month) |> 
  summarize(station_precip_total = sum(PRCP, na.rm = TRUE)) |> 
  group_by(year, month) |> 
  summarize(station_precip_total_avg = mean(station_precip_total, na.rm = TRUE)) |> 
  mutate(year_month = paste(year, month, sep = "-")) |> 
  plot_ly(
    x = ~year_month, y = ~station_precip_total_avg, color = ~as.factor(year), type = "bar"
    ) |> 
  layout(xaxis = list(title = "Date (Year, Month)"), 
         yaxis = list(title = "Total Precipitation (in)"), legend = list(title = list(text = "Year")))
```

