---
title: "Elk_leaflet"
author: "Brooklynn McNeil"
date: "2024-11-21"
output: html_document
---
Load packages and set options.

```{r setup, include=FALSE}
library(tidyverse)
library(modelr)
library(leaflet)
library(leaflet.extras2)

knitr::opts_chunk$set(
  comment = '', fig.width = 8, fig.height = 6, out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

Import elk migration data.

```{r}
elk_df = read_csv("../clean_data/elk.csv") |>
  mutate(datetime = make_datetime(year, month, day, hour)) |>
  select(elk_id, datetime, lat, long)

elk_df
```

Elk Leaflet.

```{r}
# Let's make a custom elk icon!!
moose_icon <- makeIcon(
  iconUrl = "pics/elk_icon.png", # Replace with the URL of your moose image
  iconWidth = 30, iconHeight = 30
)

elk_df |>
  filter(year(datetime) == 2006) |>
  leaflet() |>
  addProviderTiles(providers$CartoDB.Positron, group = "Base Map") |>
  addProviderTiles(providers$Esri.NatGeoWorldMap, group = "NatGeo Map") |>
   addMarkers(
    lng = ~long, lat = ~lat,
    icon = moose_icon,  # Use the custom icon
    popup = ~paste("Elk ID:", elk_id)  # Add a popup with Elk ID
  )
    
```